name: firebase_messaging_platform_interface
description: A common platform interface for the firebase_messaging plugin.
version: 4.5.29
homepage: https://github.com/firebase/flutterfire/tree/master/packages/firebase_messaging/firebase_messaging_platform_interface
repository: https://github.com/firebase/flutterfire/tree/master/packages/firebase_messaging/firebase_messaging_platform_interface

environment:
  sdk: ">=2.18.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  _flutterfire_internals: ^1.3.27
  firebase_core:
    git:
      url: https://github.com/peterscully-catapult/flutterfire
      ref: 93238b9cb0b25298f5dcdd37605e82605a8b2835
      path: packages/firebase_core/firebase_core
  flutter:
    sdk: flutter
  meta: ^1.8.0
  plugin_platform_interface: ^2.1.3

dev_dependencies:
  firebase_core_platform_interface: ^5.0.0
  flutter_test:
    sdk: flutter
  mockito: ^5.0.0
