name: firebase_messaging
description: Flutter plugin for Firebase Cloud Messaging, a cross-platform
  messaging solution that lets you reliably deliver messages on Android and iOS.
homepage: https://firebase.google.com/docs/cloud-messaging
repository: https://github.com/firebase/flutterfire/tree/master/packages/firebase_messaging/firebase_messaging
version: 14.7.21
publish_to: none

false_secrets:
  - example/**

environment:
  sdk: ">=2.18.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  firebase_core:
    git:
      url: https://github.com/peterscully-catapult/flutterfire
      ref: cbe35144bfdcc28ebaa6e7fd99f0367c7f08519e
      path: packages/firebase_core/firebase_core
  firebase_core_platform_interface: ^5.0.0
  firebase_messaging_platform_interface:
    git:
      url: https://github.com/peterscully-catapult/flutterfire
      ref: 1300c8a4a6ad7f867949582169f760248339e229
      path: packages/firebase_messaging/firebase_messaging_platform_interface
  firebase_messaging_web:
    git:
      url: https://github.com/peterscully-catapult/flutterfire
      ref: f2605805e879e511bdf624c0ec1f5d986f48a807
      path: packages/firebase_messaging/firebase_messaging_web
  flutter:
    sdk: flutter
  meta: ^1.8.0

dev_dependencies:
  async: ^2.5.0
  flutter_test:
    sdk: flutter
  mockito: ^5.0.0
  plugin_platform_interface: ^2.1.3

flutter:
  plugin:
    platforms:
      android:
        package: io.flutter.plugins.firebase.messaging
        pluginClass: FlutterFirebaseMessagingPlugin
      ios:
        pluginClass: FLTFirebaseMessagingPlugin
      macos:
        pluginClass: FLTFirebaseMessagingPlugin
      web:
        default_package: firebase_messaging_web
