name: firebase_core
description: Flutter plugin for Firebase Core, enabling connecting to multiple
  Firebase apps.
homepage: https://firebase.google.com/docs/flutter/setup
repository: https://github.com/firebase/flutterfire/tree/master/packages/firebase_core/firebase_core
version: 2.27.2
publish_to: none

false_secrets:
  - example/**

environment:
  sdk: ">=2.18.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  firebase_core_platform_interface: ^5.0.0
  firebase_core_web:
    git:
      url: https://github.com/peterscully-catapult/flutterfire
      ref: 6510623c091a413338a9e32c04836f93c6c07d99
      path: packages/firebase_core/firebase_core_web
  flutter:
    sdk: flutter
  meta: ^1.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.0
  plugin_platform_interface: ^2.1.3

flutter:
  plugin:
    platforms:
      android:
        package: io.flutter.plugins.firebase.core
        pluginClass: FlutterFirebaseCorePlugin
      ios:
        pluginClass: FLTFirebaseCorePlugin
      macos:
        pluginClass: FLTFirebaseCorePlugin
      web:
        default_package: firebase_core_web
      windows:
        pluginClass: FirebaseCorePluginCApi

firebase:
  google_services_gradle_plugin_version: "4.3.10"
  crashlytics_gradle_plugin_version: "2.8.1"
  performance_gradle_plugin_version: "1.4.1"
