name: firebase_messaging_web
description: The web implementation of firebase_messaging
homepage: https://github.com/firebase/flutterfire/tree/master/packages/firebase_messaging/firebase_messaging_web
repository: https://github.com/firebase/flutterfire/tree/master/packages/firebase_messaging/firebase_messaging_web
version: 3.7.1
publish_to: none

environment:
  sdk: ">=3.2.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  _flutterfire_internals: ^1.3.27
  firebase_core:
    git:
      url: https://github.com/peterscully-catapult/flutterfire
      ref: 93238b9cb0b25298f5dcdd37605e82605a8b2835
      path: packages/firebase_core/firebase_core
  firebase_core_web:
    git:
      url: https://github.com/peterscully-catapult/flutterfire
      ref: 93238b9cb0b25298f5dcdd37605e82605a8b2835
      path: packages/firebase_core/firebase_core_web
  firebase_messaging_platform_interface: ^4.5.29
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  js: ^0.6.3
  meta: ^1.8.0
  web: ^0.5.1

dev_dependencies:
  firebase_core_platform_interface: ^5.0.0
  flutter_test:
    sdk: flutter
  mockito: ^5.0.0

flutter:
  plugin:
    platforms:
      web:
        pluginClass: FirebaseMessagingWeb
        fileName: firebase_messaging_web.dart
