name: firebase_messaging_web
description: The web implementation of firebase_messaging
homepage: https://github.com/firebase/flutterfire/tree/master/packages/firebase_messaging/firebase_messaging_web
repository: https://github.com/firebase/flutterfire/tree/master/packages/firebase_messaging/firebase_messaging_web
version: 3.7.1

environment:
  sdk: ">=3.2.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  _flutterfire_internals:
    git:
      url: https://github.com/peterscully-catapult/flutterfire
      ref: 3cd2514c68fb4066b752884d947754541a4cb6e1
      path: packages/_flutterfire_internals
  firebase_core:
    git:
      url: https://github.com/peterscully-catapult/flutterfire
      ref: ecfe106448dc117bce6ad893971973fb4f664583
      path: packages/firebase_core/firebase_core
  firebase_core_web:
    git:
      url: https://github.com/peterscully-catapult/flutterfire
      ref: 6510623c091a413338a9e32c04836f93c6c07d99
      path: packages/firebase_core/firebase_core_web
  firebase_messaging_platform_interface:
    git:
      url: https://github.com/peterscully-catapult/flutterfire
      ref: 0a4d2cb89d0d64390f3f46b4a26f98daa403abea
      path: packages/firebase_messaging/firebase_messaging_platform_interface
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  js: ^0.7.1
  meta: ^1.8.0
  web: ^0.5.1

dev_dependencies:
  firebase_core_platform_interface: ^5.0.0
  flutter_test:
    sdk: flutter
  mockito: ^5.0.0

flutter:
  plugin:
    platforms:
      web:
        pluginClass: FirebaseMessagingWeb
        fileName: firebase_messaging_web.dart
