name: firebase_messaging_web
description: The web implementation of firebase_messaging
homepage: https://github.com/firebase/flutterfire/tree/master/packages/firebase_messaging/firebase_messaging_web
repository: https://github.com/firebase/flutterfire/tree/master/packages/firebase_messaging/firebase_messaging_web
version: 3.7.1
publish_to: none

environment:
  sdk: ">=3.2.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  _flutterfire_internals:
    git:
      url: https://github.com/peterscully-catapult/flutterfire
      ref: fb8dcdd8244d239666c8dc8b1ac83cc6e8ca1824
      path: packages/_flutterfire_internals
  firebase_core:
    git:
      url: https://github.com/peterscully-catapult/flutterfire
      ref: 6510623c091a413338a9e32c04836f93c6c07d99
      path: packages/firebase_core/firebase_core
  firebase_core_web:
    git:
      url: https://github.com/peterscully-catapult/flutterfire
      ref: e5ca11e93ae1a7f791643939bc9a269c5010bf93
      path: packages/firebase_core/firebase_core_web
  firebase_messaging_platform_interface:
    git:
      url: https://github.com/peterscully-catapult/flutterfire
      ref: 58dcd1e3507db5bd9e7761871a968be1da40e097
      path: packages/firebase_messaging/firebase_messaging_platform_interface
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  js: ^0.7.1
  meta: ^1.8.0
  web: ^0.5.1

dev_dependencies:
  firebase_core_platform_interface: ^5.0.0
  flutter_test:
    sdk: flutter
  mockito: ^5.0.0

flutter:
  plugin:
    platforms:
      web:
        pluginClass: FirebaseMessagingWeb
        fileName: firebase_messaging_web.dart
