name: firebase_messaging_web
description: The web implementation of firebase_messaging
homepage: https://github.com/firebase/flutterfire/tree/master/packages/firebase_messaging/firebase_messaging_web
repository: https://github.com/firebase/flutterfire/tree/master/packages/firebase_messaging/firebase_messaging_web
version: 3.7.1
publish_to: none

environment:
  sdk: ">=3.2.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  _flutterfire_internals:
    git:
      url: https://github.com/peterscully-catapult/flutterfire
      ref: 12b0089b1b10f6ceb2acc81ecf03bd78f1594e45
      path: packages/_flutterfire_internals
  firebase_core:
    git:
      url: https://github.com/peterscully-catapult/flutterfire
      ref: cbe35144bfdcc28ebaa6e7fd99f0367c7f08519e
      path: packages/firebase_core/firebase_core
  firebase_core_web:
    git:
      url: https://github.com/peterscully-catapult/flutterfire
      ref: 6510623c091a413338a9e32c04836f93c6c07d99
      path: packages/firebase_core/firebase_core_web
  firebase_messaging_platform_interface:
    git:
      url: https://github.com/peterscully-catapult/flutterfire
      ref: 1300c8a4a6ad7f867949582169f760248339e229
      path: packages/firebase_messaging/firebase_messaging_platform_interface
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  js: ^0.7.1
  meta: ^1.8.0
  web: ^0.5.1

dev_dependencies:
  firebase_core_platform_interface: ^5.0.0
  flutter_test:
    sdk: flutter
  mockito: ^5.0.0

flutter:
  plugin:
    platforms:
      web:
        pluginClass: FirebaseMessagingWeb
        fileName: firebase_messaging_web.dart
